# Generated by Django 4.2.7 on 2025-04-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_node_commissioning_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Designates whether the user is approved to perform basic tasks such as submitting apps to ECR.', verbose_name='Approval status')),
            ],
        ),
    ]
