# Generated by Django 4.2.7 on 2025-04-17 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_allocationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('grant_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='renew_existing_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='request_new_project',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AllocationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pi_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pi_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('project_title', models.CharField(max_length=255)),
                ('project_website', models.URLField(blank=True, null=True)),
                ('project_short_name', models.CharField(max_length=100)),
                ('science_field', models.CharField(choices=[('Physics', 'Physics'), ('Biology', 'Biology'), ('Computer Science', 'Computer Science')], max_length=50)),
                ('related_to_proposal', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('justification', models.TextField(blank=True, null=True)),
                ('access_running_apps', models.BooleanField(default=False)),
                ('access_shell', models.BooleanField(default=False)),
                ('access_download', models.BooleanField(default=False)),
                ('use_hpc', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('allocation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.allocationrequest')),
                ('funding_sources', models.ManyToManyField(to='app.fundingsource')),
            ],
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='existing_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.allocationproject'),
        ),
    ]
