# Generated by Django 4.2.7 on 2025-04-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_fundingsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='include_in_api',
            field=models.BooleanField(default=True),
        ),
    ]
