# Generated by Django 4.2.7 on 2025-04-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_project_include_in_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrequest',
            name='existing_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project'),
        ),
    ]
