# Generated by Django 4.2.7 on 2025-04-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_alter_allocationrequest_existing_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationrequest",
            name="request_add_to_existing_project",
            field=models.BooleanField(default=False),
        ),
    ]
