# Generated by Django 4.2.7 on 2025-04-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_allocationrequest_request_add_to_existing_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allocationrequest",
            name="renew_existing_project",
        ),
        migrations.RemoveField(
            model_name="allocationrequest",
            name="request_add_to_existing_project",
        ),
        migrations.RemoveField(
            model_name="allocationrequest",
            name="request_new_project",
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="project_request_type",
            field=models.CharField(
                choices=[
                    ("new", "Request new project"),
                    ("renew", "Renew existing project"),
                    ("add", "Request add to existing project"),
                ],
                default="new",
                max_length=10,
                verbose_name="Project Request Type",
            ),
        ),
    ]
