# Generated by Django 4.2.7 on 2025-04-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_remove_allocationrequest_renew_existing_project_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScienceField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="allocationproject",
            name="science_field",
        ),
        migrations.AlterField(
            model_name="allocationrequest",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Has the project been approved?",
                verbose_name="Approval status",
            ),
        ),
        migrations.AddField(
            model_name="allocationproject",
            name="science_fields",
            field=models.ManyToManyField(to="app.sciencefield"),
        ),
    ]
