# Generated by Django 4.2.7 on 2025-04-29 21:21

from django.db import migrations

def populate_science_fields(apps, schema_editor):
    ScienceField = apps.get_model('app', 'ScienceField')
    initial_fields = [
        'Physics',
        'Biology',
        'Computer Science',
    ]
    for field_name in initial_fields:
        ScienceField.objects.create(name=field_name)

def reverse_populate_science_fields(apps, schema_editor):
    ScienceField = apps.get_model('app', 'ScienceField')
    ScienceField.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('app', '0021_sciencefield_remove_allocationproject_science_field_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_science_fields, reverse_populate_science_fields),
    ]
