# Generated by Django 4.2.7 on 2025-04-29 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_populate_science_fields"),
        ("app", "rename_allocation_request_name_to_username"),
    ]

    operations = []
