# Generated by Django 4.2.7 on 2025-04-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_merge_20250429_2201"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allocationproject",
            name="use_hpc",
        ),
        migrations.AddField(
            model_name="allocationproject",
            name="interest_in_hpc",
            field=models.BooleanField(
                default=False,
                verbose_name="Are you interested in using HPC resources with Sage data?",
            ),
        ),
    ]
