# Generated by Django 4.2.7 on 2025-04-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0025_add_more_science_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocationproject",
            name="allocation_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocation_project",
                to="app.allocationrequest",
            ),
        ),
        migrations.AlterField(
            model_name="allocationproject",
            name="pi_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="allocationproject",
            name="pi_institution",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="allocationproject",
            name="pi_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
