# Generated by Django 4.2.7 on 2025-04-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0026_alter_allocationproject_allocation_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationrequest",
            name="access_download",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="access_running_apps",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="access_shell",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="funding_sources",
            field=models.ManyToManyField(to="app.fundingsource"),
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="interest_in_hpc",
            field=models.BooleanField(
                default=False,
                verbose_name="Are you interested in using HPC resources with Sage data?",
            ),
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="justification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="pi_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="pi_institution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="pi_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="project_short_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="project_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="project_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="related_to_proposal",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocationrequest",
            name="science_fields",
            field=models.ManyToManyField(to="app.sciencefield"),
        ),
        migrations.DeleteModel(
            name="AllocationProject",
        ),
    ]
