# Generated by Django 4.2.7 on 2025-04-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0027_allocationrequest_access_download_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationrequest",
            name="comments",
            field=models.TextField(
                blank=True,
                help_text="Any additional comments or information you'd like to provide",
                null=True,
                verbose_name="Additional Comments",
            ),
        ),
    ]
