# Generated by Django 4.2.7 on 2025-05-01 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0021_sciencefield_remove_allocationproject_science_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocationrequest',
            old_name='name',
            new_name='username',
        ),
    ]